### PR TITLE
Complete Detail object for Vegalite spec completion

### PR DESCRIPTION
**Pull request by aggFTW**
Will help towards completing #42 and #43

### CODE REVIEW

**Comment by ellisonbg** [comment]
Rebase...

**Comment by ellisonbg** [comment]
Rebase...

**Comment by aggFTW** [comment]
I need a merge of the other branch first. Will do that once you merge that one =)

**Comment by aggFTW** [comment]
Done Brian. Thanks!

**Comment by ellisonbg** [comment]
Merging!

**Pull request merged**
