### PR TITLE
Complete Text object for Vegalite spec completion

### PR DESCRIPTION
**Pull request by aggFTW**
Will help towards completing #42 and #43

### CODE REVIEW

**Comment by ellisonbg** [comment]
Also needs rebase...

**Comment by aggFTW** [comment]
This should be the second merge. It might have conflicts if you merged the Axis PR first.

**Comment by ellisonbg** [comment]
Yep needs another rebase...

**Comment by aggFTW** [comment]
On it

**Comment by aggFTW** [comment]
Should work now

**Pull request merged**
