### PR TITLE
Paper updates

### PR DESCRIPTION
**Pull request by domoritz**

### CODE REVIEW

**Comment by domoritz** [comment]
@ellisonbg I added and described an example. I think the paper is ready to be submitted now.

**Comment by domoritz** [comment]
cc @jakevdp

**Review by ellisonbg — APPROVED** [review]

**Comment by domoritz** [comment]
Should we merge this?

**Comment by ellisonbg** [comment]
Sure, going ahead with the merge. We can also edit more in the submission process/review if needed.

**Pull request merged**
