### PR TITLE
[MRG] Bump Vega-Lite to v1.0.10

### PR DESCRIPTION
**Pull request by jakevdp**
Bumping Vega-Lite to v1.0.10

This change touches a lot of things. The basic summary is:

- New examples & associated notebooks & tests from the Vega-Lite 1.0.10 release
- New schema & wrappers for the Vega-Lite v1.0.10 schema
- Two new top-level classes join ``Chart`` (names can easily be changed): ``LayerChart`` and ``FacetChart``. ``LayerChart`` is essentially a list of charts, while ``FacetChart`` is a ``Chart`` or ``LayerChart`` along with a row and column.
- Enhancements to the visitor code to correctly generate JSON and altair code
- Refactoring of various keyword inference codes from ``encoding``, ``transform_data``, etc. They now all make use of the same base class methods.

There are a few examples which test layering, and none to my knowledge that test faceting.

### CODE REVIEW

**Comment by ellisonbg** [comment]
Feel free to merge and iterate....

On Fri, Jun 10, 2016 at 2:06 PM, Jake Vanderplas <notifications@github.com>
wrote:

> Bumping Vega-Lite to v1.0.10
>
> All but a couple of the tests are passing; the main issues is that now the
> top-level object can be either:
>
>    - an ExtendedUnitSpec, which is essentially what we previously called
>    a Chart (and is a UnitSpec plus a row and column encoding)
>    - a LayerSpec, which includes a list of UnitSpec objects to layer
>    - a FacetSpec, which includes either a LayerSpec or a UnitSpec along
>    with a row and column encoding.
>
> The current failures are layers and facets, which will require a new
> top-level implementation. Knowing this, I'll need to think about how to
> best structure the interface and the spec ingestion code.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/ellisonbg/altair/pull/128
> Commit Summary
>
>    - Bump Vega-Lite to v1.0.10
>
> File Changes
>
>    - *M* Makefile
>    <https://github.com/ellisonbg/altair/pull/128/files#diff-0> (2)
>    - *M* altair/__init__.py
>    <https://github.com/ellisonbg/altair/pull/128/files#diff-1> (4)
>    - *M* altair/api.py
>    <https://github.com/ellisonbg/altair/pull/128/files#diff-2> (61)
>    - *A* altair/examples/json/bubble_health_income.json
>    <https://github.com/ellisonbg/altair/pull/128/files#diff-3> (37)
>    - *A* altair/examples/json/github_punchcard.json
>    <https://github.com/ellisonbg/altair/pull/128/files#diff-4> (23)
>    - *A* altair/examples/json/layer_histogram.json
>    <https://github.com/ellisonbg/altair/pull/128/files#diff-5> (43)
>    - *A* altair/examples/json/layer_line_color_rule.json
>    <https://github.com/ellisonbg/altair/pull/128/files#diff-6> (47)
>    - *A* altair/examples/json/scatter_opacity.json
>    <https://github.com/ellisonbg/altair/pull/128/files#diff-7> (20)
>    - *A* altair/examples/json/stacked_bar_size.json
>    <https://github.com/ellisonbg/altair/pull/128/files#diff-8> (28)
>    - *A* altair/examples/json/stacked_bar_sum_opacity.json
>    <https://github.com/ellisonbg/altair/pull/128/files#diff-9> (37)
>    - *A* altair/examples/json/trellis_anscombe.json
>    <https://github.com/ellisonbg/altair/pull/128/files#diff-10> (32)
>    - *M* altair/schema/_interface/__init__.py
>    <https://github.com/ellisonbg/altair/pull/128/files#diff-11> (30)
>    - *R* altair/schema/_interface/axis.py
>    <https://github.com/ellisonbg/altair/pull/128/files#diff-12> (52)
>    - *M* altair/schema/_interface/axisconfig.py
>    <https://github.com/ellisonbg/altair/pull/128/files#diff-13> (46)
>    - *R* altair/schema/_interface/bin.py
>    <https://github.com/ellisonbg/altair/pull/128/files#diff-14> (6)
>    - *M* altair/schema/_interface/cellconfig.py
>    <https://github.com/ellisonbg/altair/pull/128/files#diff-15> (6)
>    - *M* altair/schema/_interface/channeldefwithlegend.py
>    <https://github.com/ellisonbg/altair/pull/128/files#diff-16> (22)
>    - *M* altair/schema/_interface/encoding.py
>    <https://github.com/ellisonbg/altair/pull/128/files#diff-17> (17)
>    - *A* altair/schema/_interface/extendedunitspec.py
>    <https://github.com/ellisonbg/altair/pull/128/files#diff-18> (44)
>    - *A* altair/schema/_interface/facet.py
>    <https://github.com/ellisonbg/altair/pull/128/files#diff-19> (25)
>    - *A* altair/schema/_interface/facetspec.py
>    <https://github.com/ellisonbg/altair/pull/128/files#diff-20> (45)
>    - *M* altair/schema/_interface/fielddef.py
>    <https://github.com/ellisonbg/altair/pull/128/files#diff-21> (16)
>    - *R* altair/schema/_interface/formula.py
>    <https://github.com/ellisonbg/altair/pull/128/files#diff-22> (6)
>    - *A* altair/schema/_interface/interpolate.py
>    <https://github.com/ellisonbg/altair/pull/128/files#diff-23> (12)
>    - *A* altair/schema/_interface/layerspec.py
>    <https://github.com/ellisonbg/altair/pull/128/files#diff-24> (40)
>    - *A* altair/schema/_interface/legend.py
>    <https://github.com/ellisonbg/altair/pull/128/files#diff-25> (103)
>    - *M* altair/schema/_interface/legendconfig.py
>    <https://github.com/ellisonbg/altair/pull/128/files#diff-26> (71)
>    - *D* altair/schema/_interface/legendproperties.py
>    <https://github.com/ellisonbg/altair/pull/128/files#diff-27> (36)
>    - *M* altair/schema/_interface/mark.py
>    <https://github.com/ellisonbg/altair/pull/128/files#diff-28> (4)
>    - *M* altair/schema/_interface/markconfig.py
>    <https://github.com/ellisonbg/altair/pull/128/files#diff-29> (15)
>    - *M* altair/schema/_interface/orderchanneldef.py
>    <https://github.com/ellisonbg/altair/pull/128/files#diff-30> (16)
>    - *M* altair/schema/_interface/positionchanneldef.py
>    <https://github.com/ellisonbg/altair/pull/128/files#diff-31> (22)
>    - *M* altair/schema/_interface/scale.py
>    <https://github.com/ellisonbg/altair/pull/128/files#diff-32> (10)
>    - *M* altair/schema/_interface/scaleconfig.py
>    <https://github.com/ellisonbg/altair/pull/128/files#diff-33> (19)
>    - *M* altair/schema/_interface/tests/test_instantiations.py
>    <https://github.com/ellisonbg/altair/pull/128/files#diff-34> (56)
>    - *M* altair/schema/_interface/transform.py
>    <https://github.com/ellisonbg/altair/pull/128/files#diff-35> (6)
>    - *A* altair/schema/_interface/unitencoding.py
>    <https://github.com/ellisonbg/altair/pull/128/files#diff-36> (63)
>    - *A* altair/schema/_interface/unitspec.py
>    <https://github.com/ellisonbg/altair/pull/128/files#diff-37> (44)
>    - *M* altair/schema/_wrappers/__init__.py
>    <https://github.com/ellisonbg/altair/pull/128/files#diff-38> (2)
>    - *M* altair/schema/_wrappers/channel_wrappers.py
>    <https://github.com/ellisonbg/altair/pull/128/files#diff-39> (44)
>    - *M* altair/schema/_wrappers/encoding_channels.py
>    <https://github.com/ellisonbg/altair/pull/128/files#diff-40> (5)
>    - *M* altair/schema/vega-lite-schema.json
>    <https://github.com/ellisonbg/altair/pull/128/files#diff-41> (1674)
>    - *M* altair/utils/visitors.py
>    <https://github.com/ellisonbg/altair/pull/128/files#diff-42> (8)
>
> Patch Links:
>
>    - https://github.com/ellisonbg/altair/pull/128.patch
>    - https://github.com/ellisonbg/altair/pull/128.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ellisonbg/altair/pull/128>, or mute the thread
> <https://github.com/notifications/unsubscribe/AABr0HVDZAaZJxdXyyTev6mqZj_c1ifBks5qKdHDgaJpZM4IzVJG>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jakevdp** [comment]
Thanks Brian! It's going to take some thought & work before this one can be merged...

**Comment by jakevdp** [comment]
I think this is good to go, but I'd like to play with the Facet interface a bit and see how it works.

**Comment by jakevdp** [comment]
OK – there might still be small issues, but I'm going to merge and we can iterate from master.

**Pull request merged**
