### PR TITLE
ENH: allow mark configuration via mark_*() methods

### PR DESCRIPTION
**Pull request by jakevdp**
Implements idea in https://github.com/ellisonbg/altair/issues/93#issuecomment-220712808

### CODE REVIEW

**Comment by kanitw** [comment]
As mentioned [here](https://github.com/ellisonbg/altair/issues/93#issuecomment-220759153), I don't think we should do this.  At least, we should consider very hard before going down this route.

**Comment by jakevdp** [comment]
As mentioned below your comments, I feel pretty strongly that we should do this. Altair is an API, not a specification.

**Comment by ellisonbg** [comment]
I mentioned it in more depth in another thread, but I agree with Jake that
we should do this.

On Fri, May 20, 2016 at 10:39 PM, Jake Vanderplas <notifications@github.com>
wrote:

> As mentioned below your comments, I feel pretty strongly that we should do
> this. Altair is an API, not a specification.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ellisonbg/altair/pull/104#issuecomment-220760183>
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jakevdp** [comment]
If we're going to go this route, I'll need to do some tweaks on the code generation side to have it use this by default. If we're going to move forward with it, let me know and I can work on that.

**Comment by ellisonbg** [comment]
The only question I have it what to do if a user does config through the
`mark_*` methods and `configure`. Do they clobber each other? Do they get
combined? With what ordering? Same for other method+attribute combos I
guess.

On Mon, May 23, 2016 at 7:49 AM, Jake Vanderplas <notifications@github.com>
wrote:

> If we're going to go this route, I'll need to do some tweaks on the code
> generation side to have it use this by default. If we're going to move
> forward with it, let me know and I can work on that.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ellisonbg/altair/pull/104#issuecomment-221002329>
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jakevdp** [comment]
Currently, any operation clobbers previous ones. I think that's probably as good a default as we can get.

**Comment by ellisonbg** [comment]
OK sounds good - do you want to have a good at this?

On Mon, May 23, 2016 at 8:22 AM, Jake Vanderplas <notifications@github.com>
wrote:

> Currently, any operation clobbers previous ones. I think that's probably
> as good a default as we can get.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ellisonbg/altair/pull/104#issuecomment-221009095>
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jakevdp** [comment]
If you'd like to tackle it, go ahead!

**Comment by ellisonbg** [comment]
k I will have a go

On Mon, May 23, 2016 at 1:22 PM, Jake Vanderplas <notifications@github.com>
wrote:

> If you'd like to tackle it, go ahead!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ellisonbg/altair/pull/104#issuecomment-221084781>
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by ellisonbg** [comment]
OK, totally lost track of what PRs were opened and ended up doing this one myself. In master now with updated notebooks. Closing.

**Pull request closed without merging**
