### PR TITLE
Add Vega-Lite Auto Examples

### PR DESCRIPTION
**Pull request by jakevdp**
Updated auto-examples to generate notebooks from the JSON examples.

For the time being, I did not commit executed versions because the visualizations don't show up until you run them in a browser anyway.

(Though I did auto-execute all of them to confirm that the Python runs correctly)

### CODE REVIEW

**Comment by jakevdp** [comment]
For reference, here's a link to the auto-generated example index: https://github.com/jakevdp/altair/blob/122a7ad2d6f2977a53b9696a7dc053ef6af55771/notebooks/auto_examples/Index.ipynb

**Comment by jakevdp** [comment]
Oops – realized I wasn't actually running all of them. I found and fixed a small bug with datetime serialization, confirmed that all examples run, and added a link to them in the index.

**Comment by ellisonbg** [comment]
Great, should I merge?

**Comment by jakevdp** [comment]
I think it's good to go

**Pull request merged**
