### PR TITLE
MAINT: Remove old & unused code

### PR DESCRIPTION
**Pull request by jakevdp**
I don't think there's any reason to keep these around... let me know if I've overlooked something

### CODE REVIEW

**Comment by ellisonbg** [comment]
We do still need to require the ipython package because we use the display function. Other than that looks good!

**Comment by jakevdp** [comment]
I only removed the jinja2 requirement, which we no longer use. I added the ipython requirement here!

**Comment by ellisonbg** [comment]
Ahhh, sorry I missed the coloring in the diff. Merging...

**Comment by tacaswell** [comment]
:cry:

**Comment by ellisonbg** [comment]
I dare you to implement a full matplotlib rendered based on the 1.x
vega-lite spec ;-)

On Thu, May 26, 2016 at 4:25 PM, Thomas A Caswell <notifications@github.com>
wrote:

> 😢
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/ellisonbg/altair/pull/109#issuecomment-222022833>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AABr0JHRXdg2uEW1YxJCOSlmaAwxiYzzks5qFiv8gaJpZM4Ik0Xb>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by tacaswell** [comment]
That is not nice @ellisonbg, not nice at all.... :smiling_imp: 

Some what more seriously, I have not been able to keep up with this.  Is the problem of understanding/implementing the data transformations solved?

**Comment by ellisonbg** [comment]
Yes, the Vega-Lite documentation is greatly improved and descibes the
transformations very well now:

https://vega.github.io/vega-lite/docs/transform.html

On Thu, May 26, 2016 at 5:16 PM, Thomas A Caswell <notifications@github.com>
wrote:

> That is not nice @ellisonbg <https://github.com/ellisonbg>, not nice at
> all.... 😈
>
> Some what more seriously, I have not been able to keep up with this. Is
> the problem of understanding/implementing the data transformations solved?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ellisonbg/altair/pull/109#issuecomment-222029608>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AABr0CFrd-RaxNnGpkpfFTOFcD_JZSsVks5qFjfBgaJpZM4Ik0Xb>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jakevdp** [comment]
We've decided to narrow the scope and let the Vega-lite library do all the rendering for us, so we no longer have to worry about data transformations on our end.

**Comment by ellisonbg** [comment]
But if we wanted a matplotlib renderer (I would still like to see this) we would need to understand the transformation. 

Also, I have been thinking about APIs for doing things like regression (scatter + fit line). If you want that to work with different groupby's (faceting, color, etc), we would need to do those groupby's in Python, do line fits on each group and then generate a new dataset that has the fitted line data. Something like this:

```python
RegressionLayer(raw_data).mark_line().encode(
    X('raw_x:Q'),
    Y('raw_y:Q'),
    Color('groupby1'),
    Row('groupby2')
)
```

This would take the raw data, do a groupby on the color and row and then do a fit on each of those groups. All of that would give back a dataframe that would yield the fitted line data. This would require us to have the transformation layers implemented in Python.

**Pull request merged**
