### PR TITLE
MRG: Altair code generation

### PR DESCRIPTION
**Pull request by jakevdp**
This is my work-in-progress for Altair code generation.

- [x] write code to initialize a ``Layer`` object from a vega spec
- [x] write code to output an executable Altair object hierarchy from a ``Layer`` object
- [x] specialize the code generation to use top-level methods & shorthands in channels.
- [x] write automated tests & examples using schemas from vega-lite docs

Once it's finished, generation of examples & tests should be **much** easier :smile:

### CODE REVIEW

**Comment by jakevdp** [comment]
Works well so far!
```python
from altair import *

data = load_dataset('stocks')

# Transform in Vega-Lite
layer = Layer(data).mark_line()\
            .transform_data(filter="datum.symbol==='GOOG'")\
            .encode(x='date:T',
                    y='price:Q')\
            .mark_line()
D = layer.to_dict()

# create new object from the dict
Layer.from_dict(D)
```
vega 1

**Comment by jakevdp** [comment]
OK, code generation is basically working. I still need to override the function in ``Layer`` in order to use the top-level methods, but it should be pretty easy. Here's an example of what it looks like
```python
from altair import *

data = load_dataset('stocks')

layer = Layer(data).mark_line()\
            .transform_data(filter="datum.symbol==='GOOG'")\
            .encode(x='date:T',
                    y='price:Q')\
            .mark_line()

code = layer.to_altair(data='data')
print(code)
```
```
Layer(data,
  encoding=Encoding(
    x=X('',
      field='date',
      type='temporal',
    ),
    y=Y('',
      field='price',
      type='quantitative',
    ),
  ),
  mark='line',
  transform=Transform(
    filter="datum.symbol==='GOOG'",
  ),
)
```
```python
new_layer = eval(code)
layer.to_dict() == new_layer.to_dict()
# True
```

**Comment by jakevdp** [comment]
Third step is working now:
```python
from altair import *

data = load_dataset('stocks')

layer = Layer(data).mark_line().encode(
    x='date:T',
    y='price:Q'
).transform_data(
    filter="datum.symbol==='GOOG'"
).configure(
    mark=MarkConfig(color='red')
)
```
```python
>>> code = layer.to_altair(data='data')
>>> print(code)
Layer(data).mark_line().encode(
    x=X('date:T'),
    y=Y('price:Q'),
).transform_data(
    filter="datum.symbol==='GOOG'",
).configure(
    mark=MarkConfig(
        color='red',
    ),
)

>>> new_layer = eval(code)
>>> layer.to_dict() == new_layer.to_dict()
True
>>> new_layer
```
vega 2

**Comment by jakevdp** [comment]
Rebased on master to get test fixes.

**Comment by jakevdp** [comment]
Refactored a bit to make things more manageable.

**Comment by jakevdp** [comment]
Started on part 4: ingested all the vega-lite examples and wrote a test that checks that Altair correctly parses them. Good news: currently 56 of the 71 examples are passing!
The issue with the remaining 15 is that I don't yet do correct type inference for specs which contain lists. Shouldn't be too hard to fix...

**Comment by ellisonbg** [comment]
Awesome! With this working don't worry about my students doing the examples - lets auto-generate all the test and notebooks using this. Way more sustainable

**Comment by jakevdp** [comment]
After one last bug fix  and making sure the schema version matches the examples (currently v1.0.8, I believe) it looks like all tests are passing!

**Comment by jakevdp** [comment]
I'm going to change this to MRG. There are still a few other things that could happen, namely:

- make a *single* script to ingest the schema and examples. If the two have mismatched versions, it can cause weird test failures
- use the examples to auto-generate notebooks

I think those can wait for later.

**Comment by ellisonbg** [comment]
Wow, truly incredible!!! I think this is going to really help in the long run.

Should we merge and iterate or are there other things you want to do?

Also, are you thinking that we can use this to autogenerate example notebooks for all of these?

Finally, what about a cell magic like this:

```python
%%vegalite
...put a spec here...
And have the Python code for the spec magically appear in the following cell
```

**Comment by ellisonbg** [comment]
OK I will merge now...

On Sun, May 22, 2016 at 9:13 PM, Jake Vanderplas <notifications@github.com>
wrote:

> I'm going to change this to MRG. There are still a few other things that
> could happen, namely:
>
>    - make a *single* script to ingest the schema and examples. If the two
>    have mismatched versions, it can cause weird test failures
>    - use the examples to auto-generate notebooks
>
> I think those can wait for later.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/ellisonbg/altair/pull/106#issuecomment-220884077>
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jakevdp** [comment]
We can definitely generate example notebooks from these. One thing I realized, though, is the PNG won't display unless you run the notebook in the browser (and activate the javascript). Do you know if there is a way to make the javascript run programatically?

**Comment by jakevdp** [comment]
I really like the idea of a ``%%vegalite`` magic. It should be pretty easy to implement

**Comment by ellisonbg** [comment]
Yeah, I noticed the situation with the png not running until you run the
notebook in the browser. Really, we would need to start the notebook server
and then navigate to the page using a tool like phantom.js. Total pain.

On Sun, May 22, 2016 at 9:33 PM, Jake Vanderplas <notifications@github.com>
wrote:

> I really like the idea of a %%vegalite magic. It should be pretty easy to
> implement
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ellisonbg/altair/pull/106#issuecomment-220885602>
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Pull request merged**
