### PR TITLE
DOC: documents log scales

### PR DESCRIPTION
**Pull request by stsievert**
I had to plot log scales for a project of mine. I tried with Altair, but couldn't find an example and had to go digging through the source. This PR adds documentation for log scaling.

### CODE REVIEW

**Comment by stsievert** [comment]
Also, while I was searching on how to set log scales, I found docstrings useful. Should readthedocs be used to document the raw schema API? i.e., what values `Scale` takes, etc. I'd imagine that'd be low-maintenance.

**Comment by jakevdp** [comment]
I think generated documentation would be a good idea, especially since altair's doc strings seem to be more up-to-date with the spec than the vega-lite docs themselves!

**Comment by jakevdp** [comment]
I'm not sure the best way forward, though, because I think notebooks still make the most sense for narrative docs.

**Comment by jakevdp** [comment]
Note that @Carreau already made a readthedocs stub for Altair: http://altair.readthedocs.io/

**Comment by stsievert** [comment]
I would agree that notebooks make good narrative docs. I'd be tempted to include more complete documentation as well.

I've found two options for including Jupyter notebooks in Sphinx documentation:

* using nbconvert to convert to {ReST, HTML} files. ReST is native for Sphinx (table of contents comes naturally, etc) and embedding HTML seems tricky.
* using [nbsphinx], a project to include Jupyter notebooks with Sphinx. nbsphinx appears to be untested and I have filed [nbsphinx#57].

I can put some work into using readthedocs for Altair documentation.

[nbsphinx#57]:https://github.com/spatialaudio/nbsphinx/issues/57
[nbsphinx]:http://nbsphinx.readthedocs.io/en/0.2.8/
[a section]:http://nbsphinx.readthedocs.io/en/0.2.8/usage.html#Automatic-Creation-of-HTML-and-PDF-output-on-readthedocs.org

**Comment by jakevdp** [comment]
I've seen both of those – the main challenge will be appropriately setting-up and loading Vega-Lite in order to render the visualizations.

**Comment by jakevdp** [comment]
Long term we'll really want documentation that includes live vega-lite renderings rather than PNG images, especially as we begin to implement interactivity features this fall. That might require a custom sphinx plugin.

**Comment by ellisonbg** [comment]
For Altair, I would like to keep all documentation as notebooks. We (Jupyter) have been wanting to move away from readthedocs/sphinx for a while and have funding to explore how we would do that. I think that Altair is a great project to use to explore this. 

It shouldn't be too bad to autogenerate notebook based API docs from the spec - we can even use HTML output in notebook to make it look very nice. I think that will produce a nicer result than readthedocs and keep all the docs together. 

Part of the push for this is that we want to ship the docs with the python package and build a more powerful integration layer between notebook docs and the Jupyter notebook.

**Comment by stsievert** [comment]
Hm, interesting – I suppose the notebook is at least somewhat aimed at documentation.

@ellisonbg, more details on what you're envisioning? I'm imagining a tool that allows one to integrate  examples and API docs through a notebook-type interface (except with doc-related UI enhancements to make navigating easy). Docstring examples that can actually produce output would be especially refreshing.

Is this PR ready to be merged then?

**Comment by jakevdp** [comment]
Sticking with notebooks, we'll still need to figure out how to make the live Vega-Lite rendering appear somewhere online, otherwise documentation for future interactivity features will not work all that well.

**Comment by Carreau** [comment]
We'll be working with @willingc into how to get static widgets to work with a rtd theme, 
we can have a look at vegalite at the same time. 

If the json repr is in the notebook, it should be pretty straitforward to add with a custom sphinx directive the embed the json in a hidden tag.

**Comment by jakevdp** [comment]
Somehow lost in the conversation here that this is a nice addition to the notebook docs!

I'm happy to merge this, but we should make sure this discussion doesn't get lost.

**Comment by stsievert** [comment]
Agreed -- I think this is positive addition to the docs and see nothing blocking merge.

**Pull request merged**
