### PR TITLE
Expose some public methods to completion

### LINKED ISSUE #148: to_dict() not in Chart.__dir__
All in title.

### PR DESCRIPTION
**Pull request by Carreau**
Closes #148

### CODE REVIEW

**Comment by ellisonbg** [comment]
Thanks! I think the right place to do this is in api.py in the overwritten `__dir__` methods that we have there that call the base class one and add the custom methods to `Chart`, `LayeredChart` and `FacetedChart`.

**Comment by Carreau** [comment]
`Chart.__dir__` calls `super().__dir__` why not exposes this here as well ? I'm confused

**Comment by ellisonbg** [comment]
Thanks!

**Comment by ellisonbg** [comment]
Hmm, yeah, I guess the class that adds the methods should populate the dir
for those methods. And the baseobject is where those methods are defined.
Gonna merge it...

On Sat, Jul 9, 2016 at 8:32 PM, Matthias Bussonnier <
notifications@github.com> wrote:

> Chart.__dir__ calls super().__dir__ why not exposes this here as well ?
> I'm confused
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/ellisonbg/altair/pull/150#issuecomment-231565475>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AABr0LCBRRlfnT1Ll4Mm2z8-YkcmLLzpks5qUEuegaJpZM4JIvEe>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Pull request merged**
