### PR TITLE
Complete Axis object for Vegalite spec completion

### PR DESCRIPTION
**Pull request by aggFTW**
Will help towards completing #42 and #43

### CODE REVIEW

**Comment by ellisonbg** [comment]
Great work! This is coming along nicely! Merging.

**Comment by ellisonbg** [comment]
Opps, this has merge conflicts, can you rebase this on master?

**Comment by aggFTW** [comment]
Should be conflict free now. Let this PR be the first merge.

Would it help if I could merge myself? I think the next PRs will conflict with this one =)

**Comment by ellisonbg** [comment]
The way to handle a chain of PRs that would conflict is to make each new one as a branch of the previous. Then, as long as they are merged in order (just specify that in the PR) they should be fine.

**Pull request merged**
