### PR TITLE
Refactor schema parser to add docs to wrappers

### PR DESCRIPTION
**Pull request by jakevdp**
This commit adds an improved schema parser based on jinja2 templates (this doesn't add any run dependencies, but jinja2 is required to re-generate the wrappers).

One improvement is that there are now docstrings and explicit keywords in the schema objects, which means that tab-completion works! Any attribute descriptions from the schema are populated in the doc-string as well: For example:
screen shot 2016-05-25 at 4 25 40 pm
And another:
screen shot 2016-05-25 at 4 22 13 pm
This should make building visualizations much easier (though we should make similar changes at the top level as well...)

### CODE REVIEW

**Comment by jakevdp** [comment]
Looking at the diffs I realized I'm no longer wrapping the "minimum" and "maximum" attributes. I'll add that before merge.

**Comment by jakevdp** [comment]
Question on this @ellisonbg – currently we made derived versions of all the ``Channel`` methods by hand – the four classes are identical except for the class name. With the framework in this PR, I could pretty easily write a jinja2 template to auto-generate them as well, with explicit keywords for tab-completion. What do you think?

**Comment by ellisonbg** [comment]
@jakevdp that would be great - also, it would allow us to get rid of that channel mixin, which just complicates things.

**Comment by ellisonbg** [comment]
Love this approach. Also, if we ever want to add support for R, it will be very easy...

**Comment by jakevdp** [comment]
I think this is ready to merge. I'll iterate on the other ideas from master once it's in.

**Pull request merged**
