### PR TITLE
Update paper draft

### PR DESCRIPTION
**Pull request by domoritz**

### CODE REVIEW

**Comment by domoritz** [comment]
Any feedback @ellisonbg @jakevdp?

**Comment by jakevdp** [comment]
Looks good... I've always been partial to the Seattle weather plot as an example, perhaps with a link to the interactive version in the paper?

**Comment by domoritz** [comment]
I like https://altair-viz.github.io/gallery/seattle_weather_interactive.html. It's great! We just need to add a new weather type: smoke 😷

**Comment by domoritz** [comment]
@ellisonbg Can you merge this PR?

@jakevdp @ellisonbg If you think that the weather example is a good one, I can add a screenshot and write a short description. Can we aim to submit the paper this month?

**Comment by ellisonbg** [comment]
Sure, I will merge now and we can continue to iterate. I think submitting this in the coming weeks would be great!

**Pull request merged**
