### PR TITLE
Edit README

### PR DESCRIPTION
**Pull request by willingc**
This PR is a heavy edit of the README section flow and ordering.

Ran the text through Grammarly and edited.

Highlights
- Moved the visual earlier
- Added simple end user benefits/description earlier

### CODE REVIEW

**Comment by ellisonbg** [comment]
Thanks! Overall I like this re-org. Some questions and comments:

* Right now, there are no other renderers other than the Vega-Lite one :(. Because of this, I think the initial language needs to downplay that aspect of Altair (even though it is part of our philosophy and eventually I hope there are lots of renderers) and emphasize its benefits with the one renderer we have - easy to learn, API simplicity, a few clean abstractions and idea that are re-used to build complex visualizations - like lego blocks.
* Wondering if the install section should be higher up? I think there are lots of folks who would want to install it even after seeing the visual demo and reading about the features+stat vis stuff. I worry that by putting install below philisopy, users would have trouble finding it.

Thoughts?

**Comment by willingc** [comment]
Agree on both points. Reworked the initial paragraphs and moved up install section.

**Comment by willingc** [comment]
Moved the dependencies to the dev install instructions since I'm optimistic that the setup.py file will be edited to include the needed dependencies.

**Comment by willingc** [comment]
Will be away from keyboard until tomorrow :D

**Comment by ellisonbg** [comment]
Great, I will merge and iterate if needed. Thanks and see you soon!

On Sat, Jul 9, 2016 at 10:04 PM, Carol Willing <notifications@github.com>
wrote:

> Will be away from keyboard until tomorrow :D
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/ellisonbg/altair/pull/151#issuecomment-231568015>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AABr0OCbR_YjpBQnQqm26Iobz5leylZxks5qUGEzgaJpZM4JIvb1>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Pull request merged**
